# Generated by Django 6.0.7 on 2026-08-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='ai_explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='match_breakdown',
            field=models.JSONField(blank=True, help_text='Strong, Partial, and Missing matches', null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='pipeline_status',
            field=models.CharField(choices=[('APPLIED', 'Applied'), ('SHORTLISTED', 'Shortlisted'), ('INTERVIEW', 'Interviewing'), ('OFFER', 'Offer Extended'), ('HIRED', 'Hired'), ('REJECTED', 'Rejected')], default='APPLIED', max_length=20),
        ),
        migrations.AddField(
            model_name='resume',
            name='years_of_experience',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending AI Screening'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Screening Completed'), ('FAILED', 'AI Failed')], default='PENDING', max_length=20),
        ),
    ]
