# Generated by Django 6.0.7 on 2026-08-23 20:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_resume_ai_explanation_resume_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentATSCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_description', models.TextField(help_text='The job the student wants to test against.')),
                ('cv_file', models.FileField(upload_to='student_checks/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('match_score', models.IntegerField(blank=True, null=True)),
                ('missing_skills', models.JSONField(blank=True, default=list, null=True)),
                ('feedback_and_rewrites', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='resume',
            name='pipeline_status',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='match_breakdown',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
    ]
