# Generated by Django 6.0.7 on 2026-09-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_studentatscheck_remove_resume_pipeline_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='pipeline_status',
            field=models.CharField(choices=[('APPLIED', 'Applied'), ('SHORTLISTED', 'Shortlisted'), ('INTERVIEW', 'Interviewing'), ('OFFER', 'Offer Extended'), ('HIRED', 'Hired'), ('REJECTED', 'Rejected')], default='APPLIED', max_length=20),
        ),
    ]
